- .github/workflows/kube-linter.yaml
- README.md
- auto-generated/cluster/stone-prd-rh01/gbenhaim-tenant/v1_configmap_dummy-cm.yaml
- build-manifests.sh
- cluster/stone-prd-rh01/gbenhaim-tenant/dummy-cm.yaml
- cluster/stone-prd-rh01/gbenhaim-tenant/kustomization.yaml
Add basic directory structure, Readme and CI.
> RHTAP-1489: Scaffolding

- auto-generated/cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/default_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/rh-managed-red-hat-acm-tenant_appstudio.redhat.com_v1alpha1_releaseplanadmission_hypershift-operator-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/rh-managed-red-hat-acm-tenant_appstudio.redhat.com_v1alpha1_releaseplanadmission_mce-23-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/rh-managed-red-hat-acm-tenant_appstudio.redhat.com_v1alpha1_releasestrategy_push-to-external-registry-strategy.yaml
- auto-generated/cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/rh-managed-red-hat-acm-tenant_v1_persistentvolumeclaim_release-pvc.yaml
- cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/kustomization.yaml
- cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/persistent_volume_claim.yaml
- cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/release_plan_admission.yaml
- cluster/stone-prd-rh01/rh-managed-red-hat-acm-tenant/release_strategy.yaml
- this does not include service accounts or secrets definition.
> chore(HACBS-2540): added acm release resources

- auto-generated/cluster/stone-prd-rh01/rh-managed-cnv-fbc-tenant/default_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-policy.yaml
- auto-generated/cluster/stone-prd-rh01/rh-managed-cnv-fbc-tenant/rh-managed-cnv-fbc-tenant_appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-release.yaml
- auto-generated/cluster/stone-prd-rh01/rh-managed-cnv-fbc-tenant/rh-managed-cnv-fbc-tenant_appstudio.redhat.com_v1alpha1_releasestrategy_fbc-strategy.yaml
- auto-generated/cluster/stone-prd-rh01/rh-managed-cnv-fbc-tenant/rh-managed-cnv-fbc-tenant_v1_persistentvolumeclaim_release-pvc.yaml
- cluster/stone-prd-rh01/rh-managed-cnv-fbc-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/rh-managed-cnv-fbc-tenant/kustomization.yaml
- cluster/stone-prd-rh01/rh-managed-cnv-fbc-tenant/persistent_volume_claim.yaml
- cluster/stone-prd-rh01/rh-managed-cnv-fbc-tenant/release_plan_admission.yaml
- cluster/stone-prd-rh01/rh-managed-cnv-fbc-tenant/release_strategy.yaml
- this does not include service accounts or secrets definition.
> chore(HACBS-2540): added cnv-fbc release resources

- auto-generated/cluster/stone-prd-rh01/gbenhaim-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_tekton-insights.yaml
- auto-generated/cluster/stone-prd-rh01/gbenhaim-tenant/v1_configmap_dummy-cm.yaml
- cluster/stone-prd-rh01/gbenhaim-tenant/ccx-integ-test.yaml
- cluster/stone-prd-rh01/gbenhaim-tenant/dummy-cm.yaml
- cluster/stone-prd-rh01/gbenhaim-tenant/kustomization.yaml
In addition remove the configman. It was there
for a sanity test.
> Add integ-test for gbenhaim

- auto-generated/cluster/stone-prd-rh01/gbenhaim-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_tekton-insights.yaml
- cluster/stone-prd-rh01/gbenhaim-tenant/ccx-integ-test.yaml
Parameters for integration test can't be booleans.
> Change bool to string

- auto-generated/cluster/stone-prd-rh01/gbenhaim-tenant/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/cluster/stone-prd-rh01/gbenhaim-tenant/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/lib/app-interface/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/lib/consoledot-ephemeral-env-provider/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/lib/consoledot-test-pipeline/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/lib/consoledot-test-pipeline/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- lib/app-interface/app-interface.yaml
- lib/consoledot-ephemeral-env-provider/consoledot-ephemeral-env-provider.yaml
Based on the following change
https://github.com/redhat-appstudio/infra-deployments/pull/2342
> Fix the path to secrets in vault

- .github/workflows/kube-linter.yaml
The git command for checking if the auto-generated files are up to date was wrong.
> Fix the check for auto-generated files

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-staged-index-release.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releasestrategy_fbc-staged-index-strategy.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cnv-fbc-stage-index-releaseplan.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release_strategy.yaml
- cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/release_plan.yaml
- placeholder for new lenient EC policy (HACBS-2620)
- new FBC stage index release strategy for managed workspace
- new RPA for stage index release for managed workspace
- new RP for cnv-fbc workspace
> HACBS-2505: update ec-policy and RS, RP and RPA

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/ec-policy.yaml
> modify FBC policies for Red Hat configuration

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/ec-policy.yaml
> modify ACM policies for Red Hat configuration

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/ec-policy.yaml
- Remove prefetch-dependencies
- Scope the exclusion of fbc-related-image-check
> Update CNV FBC RC policies

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/ec-policy.yaml
- remove prefetch-dependencies since not required
> Update ACM EC policy

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1beta1_remotesecret_fbc-publishing-credentials-remote-secret.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/fbc-publishing-credentials-remote-secret.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/kustomization.yaml
- Switch to using RemoteSecrets for credentials
> Use RemoteSecret for fbc-publishing

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_segment-bridge-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/kustomization.yaml
> RHTAPREL-435: add default ITS for @redhat

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/ec-policy.yaml
```
include:
- '@slsa1'
- '@slsa2'
- '@slsa3'
```
> revert @redhat ruleset for EC

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-release-service-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-release-service.yaml
- add key for the slack secret for the release team
> RHTAPREL-435: Add slack secret key for release

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy.yaml
- take latest from infra-deployments
> RHTAPREL-435: update data in ec policy

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_assisted-events-scrape.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_assisted-events-stream.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/assisted-installer-tenant/appstudio.redhat.com_v1alpha1_releaseplan_assisted-events-scrape.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/assisted-installer-tenant/appstudio.redhat.com_v1alpha1_releaseplan_assisted-events-stream.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/assisted-installer-tenant/appstudio.redhat.com_v1alpha1_releaseplan_assisted-image-service.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/assisted-installer-tenant/appstudio.redhat.com_v1alpha1_releaseplan_assisted-service.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/assisted-installer-tenant/appstudio.redhat.com_v1alpha1_releaseplan_prow-jobs-scraper.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/release-plan-admission/assisted-installer-rpa.yaml
- cluster/stone-prd-rh01/tenants/assisted-installer-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/assisted-installer-tenant/release-plan.yaml
- Add release plans.
- Fix some typos in the RPA.
> Configure Assisted-Installer release

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_hypershift-operator-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_mce-23-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/release_plan_admission.yaml
- enable file-updates for MRs in app-inteface
- remove outdated ReleasePlanAdmission for mce-23
> remove older mce-23 and new file-updates

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_releasestrategy_push-to-external-registry-strategy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_releasestrategy_push-to-external-registry-strategy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releasestrategy_push-to-external-registry-strategy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/release_strategy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/release_strategy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release-strategy.yaml
- change ReleaseStrategies to use correct pyxis secret name
> align pyxis secrets to use RemoteSecrets

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy.yaml
- see https://github.com/redhat-appstudio/infra-deployments/pull/2561
> Update EC policy url

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_internal-services-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/integration_test_scenario.yaml
- add IntegrationTestScenario for internal-services
> RHTAPREL-435: add integration test

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1alpha1_releaseplan_internal-services-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1alpha1_releaseplan_release-service-release-to-quay-rhtap-ser.yaml
- cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/release_plan.yaml
- add ReleasePlan for internal-services
> RHTAPREL-435: add release plan

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-internal-services-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-internal-services.yaml
- new RPA for internal-services
> RHTAPREL-435: add releaseplanadmission

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-internal-services-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1beta1_remotesecret_send-slack-notification-secret-remote-secret.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-internal-services.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/remote-secrets/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/remote-secrets/remote_secret-send-slack-notification.yaml
- test the use of a new slack bot to send notifications
> chore(RHTAPREL-435): new prototype of send-slack-notification

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1beta1_remotesecret_pyxis-production-secret-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1beta1_remotesecret_pyxis-production-secret-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1beta1_remotesecret_pyxis-production-secret-remote-secret.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/remote-secrets/remote_secret-pyxis-secret.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/remote-secrets/remote_secret-pyxis-secret.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/remote-secrets/remote_secret-pyxis-secret.yaml
- refresh pyxis staging
- add pyxis production
> chore(RHTAPREL-627): update pyxis cert

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-internal-services-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-internal-services.yaml
> chore(RHTAPREL-435): update slack params

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-internal-services-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-release-service-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-internal-services.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-release-service.yaml
> chore(RHTAPREL-435): update slack parameters

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_terraform-provider-rhcs-rhtap.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/release-plan-admission/rhtap-migration-rpa.yaml
- Change the Terraform RPA to point to the Terraform tenant to be able to use the Custom pipeline to build
> Change Terraform RPA origin to rh-terraform-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/rh-terraform-tenant/appstudio.redhat.com_v1alpha1_releaseplan_terraform-provider-rhcs-rhtap.yaml
- cluster/stone-prd-rh01/tenants/rh-terraform-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rh-terraform-tenant/release-plan.yaml
- Remove the Terraform Release Plan from rhtap-migration-tenant
- Add the Terraform Release Plan to rh-terraform-tenant
> Add Release Plan in rh-terraform-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/rhtas-tenant/appstudio.redhat.com_v1alpha1_releaseplan_rhtas-cli-1-0-beta-registry-redhat-io.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtas-tenant/appstudio.redhat.com_v1alpha1_releaseplan_rhtas-stack-1-0-beta-registry-redhat-io.yaml
- cluster/stone-prd-rh01/tenants/rhtas-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtas-tenant/release-plan.yaml
These correspond with https://gitlab.cee.redhat.com/releng/rhtap-release-data/-/merge_requests/33
Note, auto-release is disabled here.
> Add RHTAS ReleasePlans

- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rbac.authorization.k8s.io_v1_rolebinding_rhtas-ecp.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rbac.authorization.k8s.io_v1_rolebinding_tenant-ecp.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rb-ecp.yaml
See also https://github.com/redhat-appstudio/tenants-config/pull/104 and discussion in https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1698873456488529?thread_ts=1698711241.982099&cid=C04PZ7H0VA8 for context.
> Grant rhtas-tenant tests rights to read ECP resources in releng

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1alpha1_releaseplan_internal-services-release-to-quay-rhtap-ser.yaml
- cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/release_plan.yaml
> re-add standing-attribution

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_hypershift-operator-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/release_plan_admission.yaml
- See discussion at https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1700577123371839?thread_ts=1698413546.005219&cid=C04PZ7H0VA8
> disable file-updates in ACM

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_hypershift-operator-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/release_plan_admission.yaml
As part of the rehearsal of a hypershift-operator hotfix discussed [here](https://redhat-internal.slack.com/archives/C02LM9FABFW/p1698948519158239) we need to release the hotfixed code!
> Add RPA for hypershift-operator-main-hotfix

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-staged-index-release.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release_plan_admission.yaml
add cnv-fbc-v4-15 and cnv-fbc-v4-16 to fbc-staged-index-release ReleasePlanAdmission.
> [CNV] add v4.15 and v4.16 to staging ReleasePlanAdmission

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_assisted-installer.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_bonfire-cicd-tools.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/release-plan-admission/assisted-installer-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/release-plan-admission/rhtap-migration-rpa.yaml
- Change policy for Assisted Installer apps
- Clean mix of applications in Assisted Installer RPA and RHTAP migration RPA
> Change policy for Assisted Installer apps

- auto-generated/cluster/stone-prd-rh01/tenants/centos-bootc-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_centos-bootc-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/centos-bootc-tenant/integration_test_scenario.yaml
- update the name and definition of the default IntegrationTestScenario
> RHTAPREL-741: update name and defn of its

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/ec-policy.yaml
> RHTAPREL-741: update EC policy for bifrost

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-release-to-prod.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cnv-fbc-prod-index-releaseplan-v4-11.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cnv-fbc-prod-index-releaseplan-v4-12.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cnv-fbc-prod-index-releaseplan-v4-13.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cnv-fbc-prod-index-releaseplan-v4-15.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cnv-fbc-prod-index-releaseplan-v4-16.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cnv-fbc-stage-index-releaseplan-v4-15.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cnv-fbc-stage-index-releaseplan-v4-16.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release_plan_admission_prod_index.yaml
- cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/release_plan_prod_index.yaml
- cluster/stone-prd-rh01/tenants/cnv-fbc-tenant/release_plan_stage_index.yaml
- enable *manual* prod release for 4.11-4.16
- enable *automatic* staged index releases for 4.11-4.16
> RHTAPREL-742: update cnv release resources

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/ec-policy.yaml
- See https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1700723937395219
> update ec policy for centos-bootc

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_centos-bootc.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/release-plan-admission/centos-bootc.yaml
- remove label and use floating tag
> use floating tag for centos-bootc

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fedora-bootc.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/centos-bootc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_fedora-bootc.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/release-plan-admission/fedora-bootc.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/release-plan-admission/kustomization.yaml
- cluster/stone-prd-rh01/tenants/centos-bootc-tenant/release-plan.yaml
> update for centos-bootc

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-build-trusted-artifacts-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-build-trusted-artifacts.yaml
Addressing the comment from #155
> Remove the unneeded label

- auto-generated/cluster/stone-prd-rh01/tenants/rh-terraform-tenant/appstudio.redhat.com_v1alpha1_releaseplan_terraform-provider-rhcs.yaml
- cluster/stone-prd-rh01/tenants/rh-terraform-tenant/release-plan.yaml
The name used before this one was for testing purposes
> Change name of the application in terraform release plan

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1alpha1_releaseplan_o11y-release-to-quay-rhtap-ser.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/release_plan.yaml
Added release plan for o11y component.
> chore: create release plan for o11y

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-o11y-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-o11y.yaml
Added release plan admission for o11y component.
> chore: Create release plan admission for o11y

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-ingress-go-tekton-insights.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/external-secrets.io_v1beta1_externalsecret_rh-artifacts-bucket-writer.yaml
- cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/kustomization.yaml
Insights Integration Test in Tekton for RHTAP
Used this: https://github.com/gbenhaim/tekton-insights?tab=readme-ov-file
>  Insights Integration Test in Tekton for RHTAP

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_insights-ingress-go-release-as-ms.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-ingress-go-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-ingress-go-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/integration_test_tekton.yaml
- cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/release_plan.yaml
Adding a new file for tekton integration tests
> Fixing Integration Tests

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_o11y-enterprise-contract.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy-o11y.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/integration_test_scenario.yaml
Add EC policy for o11y to mitigate the
violations due to custom tasks.
> chore: Add o11y policy file

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_o11y-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/integration_test_scenario.yaml
Updated the POLICY_CONFIGURATION param value
for o11y.
> chore: update the policy configuration value

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy-o11y.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/kustomization.yaml
ec-policy-o11y.yaml is missing in kustomization file.
> chore: add ec-policy-o11y entry in kustomization

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy-o11y.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy-o11y.yaml
Excluding tasks.required_tasks_found rule from
ec-policy-o11y.yaml file.
> chore: Exclude a rule from ec-policy for o11y

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-has-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_application-service-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-has-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-has-tenant/kustomization.yaml
See https://issues.redhat.com/browse/DEVHAS-588
This PR adds the tenant configuration for HAS in rhtap-has-tenant.
> chore: Enable tenant configuration for HAS

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-o11y-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-o11y.yaml
Updated ec policy for release plan and release
plan admission for o11y.
> chore: Update ec policy for o11y

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-ingress-go-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/integration_test_scenario.yaml
what: Adding policy Configuration
> Fix policy

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-ingress-go-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-hcc-pipeline-tenant/integration_test_scenario.yaml
> move params

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-o11y-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-o11y.yaml
Updated o11y infra-deployment-update-script to update commit ref for development and staging env
> fix: update o11y infra deployment update script

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-staged-index-release.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release_plan_admission_stage_index.yaml
This PR increases the timeout when waiting for the 
InternalRequest and IIB build to finish.
> chore: increases timeout waiting for IIB

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_ingress-release-as-ms.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_ingress-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_ingress-tekton-insights.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/external-secrets.io_v1beta1_externalsecret_rh-artifacts-bucket-writer.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/integration_test_tekton.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/release_plan.yaml
Renaming folder to match new workspace, as well as changing all other files to match new workspace.
> Renaming folder and changing namespace name to new workspace

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/ec-policy.yaml
EC deprecated SLSA1 and SLSA2 this PR
removes those from ec-policy.
> chore(RHTAPREL-681): remove SLSA1 and SLSA2 deprecated by ec

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_bootc-image-builder.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_centos-bootc.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fedora-bootc.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/release-plan-admission/bootc-image-builder.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/release-plan-admission/centos-bootc.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/release-plan-admission/fedora-bootc.yaml
Replace the floatingTag field with floatingTags in the ReleasePlanAdmissions.
> refactor(RHTAPREL-762): replace floatingTag in RPAs

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_playbook-dispatcher-release-as-ms.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_playbook-dispatcher-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_playbook-dispatcher-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/playbook_dispatcher_integration_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/playbook_dispatcher_release_plan.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/playbook_dispatcher_tekton_test.yaml
Adding release plan, integration test, tekton test for Playbook Dispatcher in hcc-pipeline ws
> Adding Playbook Dispatcher files

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-has-tenant/appstudio.redhat.com_v1alpha1_releaseplan_application-service-release-to-quay-konflux-ser.yaml
- cluster/stone-prd-rh01/tenants/rhtap-has-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtap-has-tenant/release_plan.yaml
Adds a ReleasePlan resource for HAS under the rhtap-has workspace
> chore: create ReleasePlan for HAS

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-migration-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_consoledot-frontend-standard.yaml
- cluster/stone-prd-rh01/tenants/rhtap-migration-tenant/consoledot-frontend-standard.yaml
add EC policy for the HAC team
> chore(KONFLUX-2117): add EC policy for HAC

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_internal-services-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_release-service-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-spi-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_remotesecret-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-spi-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_spi-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-spi-tenant/integration_test_scenario.yaml
- add new param POLICY_CONFIGURATION pointing to rhtap-releng-tenant/registry-standard
> fix(KFLUXBUGS-1109): use ec policy from releng directly

- auto-generated/cluster/stone-prd-rh01/tenants/trusted-content-tenant/appstudio.redhat.com_v1alpha1_component_trustification-service.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/trusted-content-tenant/appstudio.redhat.com_v1alpha1_component_trustification-tests.yaml
- cluster/stone-prd-rh01/tenants/trusted-content-tenant/apps.yaml
> Visibility change of the trustification repos

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_o11y-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/integration_test_scenario.yaml
Update integration test scenario to match the policy with release plan policy
> chore(RHTAPWATCH-840): Update Integration test scenario policy

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-remotesecret-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-spi-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-remotesecret.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-spi.yaml
{SUBJ}
Context https://issues.redhat.com/browse/SVPI-722
> Fix url after migration to github.com/konflux-ci organization

- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_infra-deployments-pr-creator-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_quay-token-secret-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rbac.authorization.k8s.io_v1_rolebinding_konflux-servicerelease-rb.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/v1_serviceaccount_konflux-servicerelease-sa.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rb-konflux-service-release.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/kustomization.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-infra-deployments-pr-creator.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-quay-token-konflux-service-release.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/sa-konflux-service-release.yaml
- Add service account for the knoflux services `konflux-servicerelease-sa` to rhtap-releng-tenant
- Add role binding for `konflux-servicerelease-sa` to rhtap-releng-tenant
-  Update customization.yaml with a new entry.
-  Add remoteSecret
> feat(RHTAPREL-723): add konflux service release sa rb rs to releng

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-integration-service-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-integration-service.yaml
Path to integration service - staging changed
> feat(STONEINTG-811): integration - update staging path

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-staged-index-release-v4-15-plus.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release_plan_admission_stage_index_v4_15_plus.yaml
- moving binaryImage: "registry.redhat.io/openshift4/ose-operator-registry:vxxx" to be registry.redhat.io/openshift4/ose-operator-registry-rhel9:vxxx"
> Separate RPA for CNV for olm v4.15+

- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_build-team-slack-webhook-notification-secret-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_pipeline-team-slack-webhook-notification-secret-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_release-team-slack-webhook-notification-secret-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_spi-team-slack-webhook-notification-secret-remote-secret.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/kustomization.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-build-team-slack-webhook-notification.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-pipeline-team-slack-webhook-notification.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-release-team-slack-webhook-notification.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-spi-team-slack-webhook-notification.yaml
Migrate Slack notification RemoteSecrets
- remote_secret-build-team-slack-webhook-notification.yaml
- remote_secret-pipeline-team-slack-webhook-notification.yaml
- remote_secret-release-team-slack-webhook-notification.yaml
- remote_secret-spi-team-slack-webhook-notification.yaml
> add slack notification secrets

- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_integration-team-slack-webhook-notification-secret-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rbac.authorization.k8s.io_v1_rolebinding_konflux-integration-service-rb.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/v1_serviceaccount_konflux-integration-service-sa.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rb-konflux-integration-service.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/kustomization.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-integration-team-slack-webhook-notification.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/sa-konflux-integration-service.yaml
* Add sa, rb and remote secret for integration team slack notification
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
> feat(STONEINTG-745): add resource for slack notification webhook of integration

- auto-generated/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_multiarch-tuning-operator-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/kustomization.yaml
This PR is related to the Multiarch Tuning Operator onboarding, as in https://issues.redhat.com/browse/KONFLUX-2316 and https://issues.redhat.com/browse/MULTIARCH-4161
> Adds kustomization for the multiarch tuning operator's IntegrationTestScenario

- auto-generated/cluster/stone-prd-rh01/tenants/konflux-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_project-controller-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/konflux-o11y-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/konflux-o11y-tenant/kustomization.yaml
Update default Integration Test Scenario for Enterprise Contract Validation for project-controller
> chore: Enable tenant configuration for project-controller

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1alpha1_releaseplan_project-controller-release-to-quay-rhtap-ser.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/release_plan.yaml
Release plan for project-controller is created in
rhtap-o11y
> chore: Create release plan for project-controller

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-storage-broker-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/storage_broker_tekton_test.yaml
Changing Application name to insights-ingress-go
> changing application name

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-storage-broker-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/storage_broker_tekton_test.yaml
> Adding IQE params

- auto-generated/cluster/stone-prd-rh01/tenants/tekton-ecosystem-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_ecosystem-images-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/tekton-ecosystem-tenant/integration_test_scenario_ecosystem.yaml
- cluster/stone-prd-rh01/tenants/tekton-ecosystem-tenant/kustomization.yaml
Update Integration Test Scenario for Enterprise Contract Validation for tekton-ecosystem workspace and ecosystem-images application
> Update kustomization yaml to add integration tests for new application

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-staged-index-release-v4-15-plus.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-staged-index-release.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release_plan_admission_stage_index.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release_plan_admission_stage_index_v4_15_plus.yaml
Update CNV-FBC-Stage RPA to add new data components.
> fix: update rpa with correct data

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_insights-ingress-go-sc-release-as-ms.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-ingress-go-sc-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-ingress-go-sc-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/ingress_sc_integration_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/ingress_sc_release_plan.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/ingress_sc_tekton_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/kustomization.yaml
Adding Ingress Sc APP release, tests
> Adding Ingress SC app

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_insights-ingress-go-sc-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/ingress_sc_tekton_test.yaml
Adding a component to tekton test
> Bonfire Component Name addition testing

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-contract-tenant/appstudio.redhat.com_v1alpha1_releaseplan_ec-v02-registry-redhat-io.yaml
- cluster/stone-prd-rh01/tenants/rhtap-contract-tenant/release_plan.yaml
See also:
- https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/235
- https://issues.redhat.com/browse/EC-432
- #181
> Add new release plan for ec-cli v0.2

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1alpha1_application_workspace-manager.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1alpha1_component_workspace-manager.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1alpha1_releaseplan_workspace-manager-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_workspace-manager-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/release_plan.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/workspace-manager.yaml
https://github.com/konflux-ci/workspace-manager
> Add manifests for the workspace-manager project

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_storage-broker-release-as-ms.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_storage-broker-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_storage-broker-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/storage_broker_integration_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/storage_broker_release_plan.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/storage_broker_tekton_test.yaml
Changing the storage broker name to match component name
> Changing storage broker name

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_notifications-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_notifications-tekton-insights.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/external-secrets.io_v1beta1_externalsecret_rh-artifacts-bucket-writer.yaml
- cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/notifications-enterprise-contract_integration_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/notifications-tekton-insights_integration_test.yaml
This PR adds the `hcc-notifications` tenant.
> RHCLOUD-30193 Add hcc-notifications tenant

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-devprod-tenant/appstudio.redhat.com_v1alpha1_releaseplan_frontend-operator-release-as-ms.yaml
- cluster/stone-prd-rh01/tenants/hcc-devprod-tenant/frontend_operator_release_plan.yaml
- cluster/stone-prd-rh01/tenants/hcc-devprod-tenant/kustomization.yaml
This adds an entry for the frontend-operator as part of the konflux onboarding process.
> Onboard frontend-operator

- auto-generated/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_multiarch-tuning-operator-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/integration_test_scenario.yaml
cc @ernesgonzalez33 @arewm @ralphbean 
would this other pipeline allow us not to be forced to use hermetic/disconnected builds?
> No hermetic for multiarch-tuning-operator

- auto-generated/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/appstudio.redhat.com_v1alpha1_releaseplan_fbc-v4-16-release-as-fbc.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/appstudio.redhat.com_v1alpha1_releaseplan_fbc-v4-16-release-as-staging-fbc.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/release_plan_operator.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/release_plan_staging_fbc_4_16.yaml
This PR:
1. Adds an RP referencing the staging RPA for the FBC
2. Fixes the previous RPs that were missing a reference to their RPAs
> Fix ReleasePlans for MTO

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy-cnv.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy.yaml
- build-manifests.sh
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/ec-policy.yaml
- get-kustomize.sh
- fbc fragments do not yield source containers
> exclude source_image.exists for fbc

- auto-generated/cluster/stone-prd-rh01/tenants/sfo-security-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_sfo-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/sfo-security-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/sfo-security-tenant/kustomization.yaml
Adding splunk-forwarder-operator per Konflux onboarding instructions for integration pipeline
> Adding sfo-security tenant per konflux onboarding instructions

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cloud-connector-release-as-ms.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_export-service-release-as-ms.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-tekton-insights.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_export-service-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_export-service-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_integration_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_release_plan.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_tekton_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/export_service_integration_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/export_service_release_plan.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/export_service_tekton_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/kustomization.yaml
Added two new components 
- cloud connector 
- export service
Added the enterprise contract, tekton test and the release plan for both 
Edited the kustomization file to reflect the new files
Changed ingress-sc github from dcervantes to gbenhaim
> Adding export service and cloud connector

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_build-service-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/integration_test_scenario.yaml
STONEBLD-1987
The application was renamed in 83629e5b5be00460af8bb73bf2607bfa52e7d5fc.
Rename the IntegrationTestScenario as well.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>
> rhtap-build: fix build-service ITS name

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-tekton-insights.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_export-service-tekton-insights.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_storage-broker-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_tekton_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/export_service_tekton_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/storage_broker_tekton_test.yaml
> Update iqe plugin

- auto-generated/cluster/stone-prd-rh01/tenants/sfo-security-tenant/appstudio.redhat.com_v1alpha1_releaseplan_sfo-release-as-service.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/sfo-security-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_sfo-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/sfo-security-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/sfo-security-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/sfo-security-tenant/release_plan.yaml
Adding release plan and edited integration pipeline per Konflux onboarding instructions
> Adding release plan and edited integration pipeline to reflect policy

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-tekton-insights.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_storage-broker-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_tekton_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/storage_broker_tekton_test.yaml
> chaning the params

- auto-generated/cluster/stone-prd-rh01/tenants/insights-runtimes-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_runtimes-inventory-operator-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/insights-runtimes-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/insights-runtimes-tenant/kustomization.yaml
* Adds an IntegrationTestScenario for the runtimes-inventory-operator application in the insights-runtimes workspace.
> Add IntegrationTestScenario for runtimes-inventory-operator

- auto-generated/cluster/stone-prd-rh01/tenants/crt-nshift-lightspeed-tenant/appstudio.redhat.com_v1alpha1_releaseplan_ols-releaseplan.yaml
- cluster/stone-prd-rh01/tenants/crt-nshift-lightspeed-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/crt-nshift-lightspeed-tenant/release-plan.yaml
Initial ReleasePlan for OLS.
Closes : https://issues.redhat.com/browse/OLS-391
> [ols] Add ols releaseplan for lightspeed-operator

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_o11y-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/integration_test_scenario.yaml
Depends on: https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/476
> chore: move o11y to policy deployed from gitlab

- auto-generated/cluster/stone-prd-rh01/tenants/ocm-cli-clients-tenant/appstudio.redhat.com_v1alpha1_releaseplan_ocm-cli.yaml
- cluster/stone-prd-rh01/tenants/ocm-cli-clients-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/ocm-cli-clients-tenant/release-plan.yaml
Reference: https://issues.redhat.com/browse/OCM-7821
> Add release plan for ocm-cli client

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_platform-feedback-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/kustomization.yaml
Add IntegrationTestScenario for platform-feedback and add hcc-accessmanagement as tenant
> Add IntegrationTestScenario for platform-feedback

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_storage-broker-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/storage_broker_tekton_test.yaml
> IQE Plugin

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_storage-broker-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/storage_broker_tekton_test.yaml
Testing a new pieplien with my own rep
> Adding a new pipeline

- auto-generated/cluster/stone-prd-rh01/tenants/sfo-security-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_sfo-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/sfo-security-tenant/integration_test_scenario.yaml
Fixing policy config line to allow integration tests to work
> Fixing policy config line

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_tekton_test.yaml
> Fixing component name

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_tekton_test.yaml
Removing Bonfire Component to test out tekton test. Again Apologize for the testing
> Remove env variable

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_tekton_test.yaml
Fixing Env For tekton Test Debugging
> Fixing ENV Variables

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cloud-connector-release-as-ms.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_integration_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_release_plan.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_tekton_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/kustomization.yaml
Adding component back with name change
> adding cloud connector

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_tekton_test.yaml
This should revert 86e987ca61ecca00c614bf7805edd7a075e3d754
> Revert previous cloud-connector commit

- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1alpha1_releaseplan_serverless-workflows.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/release-plan.yaml
Signed-off-by: Roy Golan <rgolan@redhat.com>
> Add orchestrator-releng tenant

- auto-generated/cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/appstudio.redhat.com_v1alpha1_releaseplan_maestro.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/release-plan.yaml
Resolves issue found [here](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1717069227626079).
> Update maestro RP to correctly reference the application

- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1alpha1_releaseplan_orchestrator-helm-operator.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/operator/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/operator/release-plan.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/serverless-workflows/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/serverless-workflows/release-plan.yaml
> Add RHDH Orchestrator operator release plan to orchestrator-releng-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1alpha1_releaseplan_orchestrator-helm-operator.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1alpha1_releaseplan_serverless-workflows.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/operator/release-plan.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/serverless-workflows/release-plan.yaml
Signed-off-by: Roy Golan <rgolan@redhat.com>
> Fix the target namespace for orchestrator-releng release plans

- auto-generated/cluster/stone-prd-rh01/tenants/rh-hms-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_provisioning-frontend-bonfire-tekton.yaml
- cluster/stone-prd-rh01/tenants/rh-hms-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rh-hms-tenant/provisioning-frontend-integration.yaml
Add integration test scenario for provisioning frontend repo(pr_check)
> Add provisioning frontend test

- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_orchestrator-helm-operator-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_serverless-workflows-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/operator/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/operator/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/serverless-workflows/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/serverless-workflows/kustomization.yaml
- **orchestrator-releng: Add integration test scenario**
>  orchestrator-releng: Add integration test scenario 

- auto-generated/cluster/stone-prd-rh01/tenants/rh-hms-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_content-sources-backend-bonfire-tekton.yaml
- cluster/stone-prd-rh01/tenants/rh-hms-tenant/content-sources-backend.yaml
- cluster/stone-prd-rh01/tenants/rh-hms-tenant/kustomization.yaml
Add integration test scenario for content-sources backend repo.
> Adding Content-sources backend test

- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_orchestrator-helm-operator-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/operator/integration_test_scenario.yaml
> Change ECP for the operator to fbc-stage in orchestrator-releng tenant

- auto-generated/cluster/stone-prd-rh01/tenants/oeo-cicada-tenant/appstudio.redhat.com_v1alpha1_releaseplan_oeo-release-as-service.yaml
- cluster/stone-prd-rh01/tenants/oeo-cicada-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/oeo-cicada-tenant/release_plan.yaml
add the releaseplan as per documentation
> oeo-cicada: add osd-example-operator ReleasePlan

- auto-generated/cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_osde2e-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/kustomization.yaml
> osde2e: onboard initial EC integration test

- auto-generated/cluster/stone-prd-rh01/tenants/oeo-cicada-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_oeo-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/oeo-cicada-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/oeo-cicada-tenant/kustomization.yaml
add EC pointing to app-interface-standard
> oeo-cicada: add enterprise contract

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_build-task-dockerfile-e2e-test.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/integration_test_scenario.yaml
The repo was migrated from the redhat-appstudio org to konflux-ci
STONEBLD-2370
> Change build-tasks-dockerfiles repo url

- auto-generated/cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_api-frontend-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/kustomization.yaml
Add IntegrationTestScenario for api-frontend
> Add IntegrationTestScenario for api-frontend

- auto-generated/cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/appstudio.redhat.com_v1alpha1_releaseplan_api-frontend-release-as-ms.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_api-frontend-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/api-frontend_release_plan.yaml
- cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/kustomization.yaml
Added API frontend release plan
@ernesgonzalez33 please, would you have time to take a look? Thank you 🙂
> Add API frontend release plan

- auto-generated/cluster/stone-prd-rh01/tenants/trusted-content-tenant/appstudio.redhat.com_v1alpha1_component_trustification-product-1-1-z.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/trusted-content-tenant/appstudio.redhat.com_v1alpha1_component_trustification-product-test-1-1-z.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/trusted-content-tenant/appstudio.redhat.com_v1alpha1_releaseplan_trustification-1-1-z.yaml
- cluster/stone-prd-rh01/tenants/trusted-content-tenant/apps.yaml
- cluster/stone-prd-rh01/tenants/trusted-content-tenant/release-plan.yaml
> rhtpa-1.1.z

- auto-generated/cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_api-frontend-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/integration_test_scenario.yaml
Use consoledot-frontend-standard policy for PlatformExperience api-frontend
> Use consoledot-frontend-standard policy

- auto-generated/cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/appstudio.redhat.com_v1alpha1_releaseplan_acrobot-release-as-service.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_acrobot-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/release_plan.yaml
Continuing to follow the Konflux onboarding guide:
* Update integration test with selected enterprise contract.
* Add release plan.
> Continue acrobot-slack onboarding

- auto-generated/cluster/stone-prd-rh01/tenants/assisted-installer-tenant/appstudio.redhat.com_v1alpha1_component_assisted-service-saas-hotfix.yaml
- cluster/stone-prd-rh01/tenants/assisted-installer-tenant/saas/apps/cloud_hotfix_releases/assisted-service-saas-hotfix.yaml
Fix component name as it is referenced in the RPA mapping (and to be consistent with other assisted installer component)
> fix(assisted-installer): Fix component name for saas hotfix

- auto-generated/cluster/stone-prd-rh01/tenants/rh-pulp-services-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_pulp-bonfire-tekton.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rh-pulp-services-tenant/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rh-pulp-services-tenant/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rh-pulp-services-tenant/external-secrets.io_v1beta1_externalsecret_rh-artifacts-bucket-writer.yaml
- cluster/stone-prd-rh01/tenants/rh-pulp-services-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rh-pulp-services-tenant/pulp-bonfire-tekton.yaml
> Add rh-pulp-services-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/appstudio.redhat.com_v1alpha1_releaseplan_osde2e-release-as-service.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/release_plan.yaml
> SDCICD-1306: add osde2e release plan

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1alpha1_releaseplan_source-container-build-release-to-quay-rhtap-ser.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/release_plan.yaml
> Add RP for source container build

- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_clio-wrklds-pipeline-prod.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/release-plan.yaml
This PR adds ReleasePlan for cli manager.
> WRKLDS-1309: Add release plan for cli manager (aka clio)

- auto-generated/cluster/stone-prd-rh01/tenants/pulp-services-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_pulp-bonfire-tekton.yaml
- cluster/stone-prd-rh01/tenants/pulp-services-tenant/pulp-bonfire-tekton.yaml
We have none, and it was trying to run a related service's tests
PULP-110
> Disable IQE tests for Pulp

- auto-generated/cluster/stone-prd-rh01/tenants/dvo-obsint-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_deployment-validation-operator-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/dvo-obsint-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/dvo-obsint-tenant/kustomization.yaml
This is part of the on-boarding of deployment-validation-operator from Observability Intelligence Data Collection team.
* [KONFLUX-2597](https://issues.redhat.com/browse/KONFLUX-2597)
* [DVO-213](https://issues.redhat.com/browse/DVO-213)
> Add kustomization for deployment-validation-operator IntegrationTestScenario

- auto-generated/cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_siteconfig-main-unit-test.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/siteconfig.unit-test.integrationtestscenario.yaml
This PR introduces configurations to run unit-tests for the siteconfig operator.
/cc @gurnben @ralphbean
> Configure siteconfig unit test

- auto-generated/cluster/stone-prd-rh01/tenants/mdepaulo-tenant/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/mdepaulo-tenant/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/mdepaulo-tenant/external-secrets.io_v1beta1_externalsecret_rh-artifacts-bucket-writer.yaml
- cluster/stone-prd-rh01/tenants/mdepaulo-tenant/kustomization.yaml
(I'm using my personal workspace to develop/test
features for pulp-services-tenant)
PULP-125
> Add kustomization for mdepaulo-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_policy-check.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/serverless-workflows/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/serverless-workflows/policy-check.yaml
Signed-off-by: Roy Golan <rgolan@redhat.com>
> Add a policy check for orchestrator releng serverless workflows

- auto-generated/cluster/stone-prd-rh01/tenants/pulp-services-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_pulp-bonfire-tekton.yaml
- cluster/stone-prd-rh01/tenants/pulp-services-tenant/pulp-bonfire-tekton.yaml
> Update for custom Pulp bonfire-tekton pipeline

- auto-generated/cluster/stone-prd-rh01/tenants/pulp-services-tenant/appstudio.redhat.com_v1alpha1_releaseplan_pulp-release-as-service.yaml
- cluster/stone-prd-rh01/tenants/pulp-services-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/pulp-services-tenant/release_plan.yaml
PULP-111
[ReleasePlanAdmission MR](https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/735)
> Add a pulp release plan

- auto-generated/cluster/stone-prd-rh01/tenants/cid-cloudx-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_cloud-image-directory-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/cid-cloudx-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/cid-cloudx-tenant/kustomization.yaml
**Summary**
Adding the tenant configuration for the Cloud Image Directory project.
**Changes**
Add cid-cloudx-tenant kustomization
Add integration_test_scenario for cloud-image-directory app
CLOUDX-981
> Onboard cid-cloudx tenant kustomization

- auto-generated/cluster/stone-prd-rh01/tenants/console-platex-services-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_pdf-generator-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/console-platex-services-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/console-platex-services-tenant/kustomization.yaml
> Onboard console-platex-services pdf-generator tenant kustomization

- auto-generated/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/projctl.konflux.dev_v1beta1_projectdevelopmentstreamtemplate_file-based-catalog.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/_base/projectl.konflux.dev/projectdevelopmentstreamtemplates/file-based-catalog/projectdevelopmentstreamtemplate.yaml
This PR adds the IntegrationTestScenarios and ReleasePlans into the ProjectDevelopmentStreamTemplate for the file-based-catalog project of the Multiarch Tuning Operator.
> Add integration scenarios and ReleasePlan in the ProjectDevelopmentStreamTemplate

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_payload-tracker-frontend-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/payload-tracker-frontend_integration_test.yaml
Part of [RHCLOUD-32758](https://issues.redhat.com/browse/RHCLOUD-32758)
Added integration tests scenario for payload-tracker frontend
cc @scoheb @gbenhaim
> Add integration tests scenario for payload-tracker FE

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/appstudio.redhat.com_v1alpha1_application_entitlements-api-go.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/appstudio.redhat.com_v1alpha1_component_entitlements-api-go.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/appstudio.redhat.com_v1alpha1_imagerepository_imagerepository-for-entitlements-api-go-entitlements-api-go.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_entitlements-api-go-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/entitlements-api-go.yaml
- cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/entitlements_api_go_integration_test.yaml
- cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/kustomization.yaml
Created component and application as code for entitlements-api-go (name for both application and component) 
- created file: entitlements-api-go.yaml 
Updated default integration test in tenants config for entitlements-api-go 
- created file: entitlements_api_go_integration_test.yaml 
Added both files to kustomization.yaml 
Doc referenced: https://gitlab.cee.redhat.com/konflux/docs/users/-/blob/main/topics/getting-started/components-applications.md#manually-create-your-first-component-and-application
> Create components/applications as code and upate default integration test in tenants config

- auto-generated/cluster/stone-prd-rh01/tenants/ocp-obsint-processing-tenant/appstudio.redhat.com_v1alpha1_application_insights-behavioral-spec.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/ocp-obsint-processing-tenant/appstudio.redhat.com_v1alpha1_component_insights-behavioral-spec.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/ocp-obsint-processing-tenant/appstudio.redhat.com_v1alpha1_imagerepository_imagerepository-for-insights-behavioral-spec-insights-behavioral-spec.yaml
- cluster/stone-prd-rh01/tenants/ocp-obsint-processing-tenant/insights-behavioral-spec-component.yaml
- cluster/stone-prd-rh01/tenants/ocp-obsint-processing-tenant/kustomization.yaml
- Tenant for `ocp-obsint-processing` workspace 
- First component [insights-behavioral-spec](https://github.com/RedHatInsights/insights-behavioral-spec)
Part of [KONFLUX-196](https://issues.redhat.com/browse/KONFLUX-196)
> Add ocp-obsint-processing tenant with first component

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-contract-tenant/appstudio.redhat.com_v1alpha1_releaseplan_golden-container-konflux-ci.yaml
- cluster/stone-prd-rh01/tenants/rhtap-contract-tenant/release_plan.yaml
Add ReleasePlan for ec golden container image
[golden-container](https://github.com/enterprise-contract/golden-container) source code change pr: https://github.com/enterprise-contract/golden-container/pull/663/files
ReleasePlanAdmisson MR: https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/869
Ticket id: https://issues.redhat.com/browse/EC-730
> add release plan for golden container image

- auto-generated/cluster/stone-prd-rh01/tenants/ose-osc-tenant/appstudio.redhat.com_v1alpha1_releaseplan_trustee-prod-release-plan.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/ose-osc-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_trustee-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/ose-osc-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/ose-osc-tenant/trustee-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/ose-osc-tenant/trustee-prod-release-plan.yaml
- Add release plan for prod.
- Change policy to allow online builds.
> Update tenant ose-osc

- auto-generated/cluster/stone-prd-rh01/tenants/rh-openshift-builds-tenant/appstudio.redhat.com_v1alpha1_releaseplan_openshift-builds-prod.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rh-openshift-builds-tenant/appstudio.redhat.com_v1alpha1_releaseplan_openshift-builds-stage.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rh-openshift-builds-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_openshift-builds-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rh-openshift-builds-tenant/integrationtestscenario.yaml
- cluster/stone-prd-rh01/tenants/rh-openshift-builds-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rh-openshift-builds-tenant/release_plan-prod.yaml
- cluster/stone-prd-rh01/tenants/rh-openshift-builds-tenant/release_plan-stage.yaml
add releaseplan for rh-openshift-builds-tenant
- releaseplan
- integrationtestscenario
> add releaseplan for rh-openshift-builds-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/obsint-processing-tenant/appstudio.redhat.com_v1alpha1_application_io-gathering-service.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/obsint-processing-tenant/appstudio.redhat.com_v1alpha1_component_io-gathering-service.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/obsint-processing-tenant/appstudio.redhat.com_v1alpha1_imagerepository_imagerepository-for-io-gathering-service-io-gathering-service.yaml
- cluster/stone-prd-rh01/tenants/obsint-processing-tenant/io-gathering-service-component.yaml
- cluster/stone-prd-rh01/tenants/obsint-processing-tenant/kustomization.yaml
Adding component  for obsint-processing workspace [io-gathering-service](https://github.com/RedHatInsights/insights-operator-gathering-conditions-service)
Part of [KONFLUX-196](https://issues.redhat.com/browse/KONFLUX-196)
> [CCXDEV-13025] Add new app io-gathering-service to obsint-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/insights-core-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_insights-puptoo-tekton-testing.yaml
- cluster/stone-prd-rh01/tenants/insights-core-tenant/insights-puptoo-app-bonfire-tekton.yaml
- fix the error: deploy failed: component given for --set-template-ref not found in app config: insights-puptoo
> fix: correct the component name

- auto-generated/cluster/stone-prd-rh01/tenants/ose-osc-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_trustee-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/ose-osc-tenant/trustee-enterprise-contract.yaml
Update policy to match release RPA.
> ose-osc-tenant: use custom policy

- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_fbc-v4-17-release-as-fbc.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_fbc-v4-17-release-as-staging-fbc.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cli-manager-operator-fbc-v4-17-ec.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/projctl.konflux.dev_v1beta1_projectdevelopmentstream_cli-manager-operator-fbc-v4-17.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/projctl.konflux.dev_v1beta1_projectdevelopmentstreamtemplate_cli-manager-operator-fbc-dst.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/projectl.konflux.dev/projectdevelopmentstreams/file-based-catalog-v4-17/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/projectl.konflux.dev/projectdevelopmentstreams/file-based-catalog-v4-17/projectdevelopmentstream.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/projectl.konflux.dev/projectdevelopmentstreamtemplates/file-based-catalog/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/projectl.konflux.dev/projectdevelopmentstreamtemplates/file-based-catalog/projectdevelopmentstreamtemplate.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/fbc_4_17/appstudio.redhat.com/integrationtestscenarios/fbc-v4-17-enterprise-contract/integrationtestscenario.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/fbc_4_17/appstudio.redhat.com/integrationtestscenarios/fbc-v4-17-enterprise-contract/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/fbc_4_17/appstudio.redhat.com/releaseplans/fbc-v4-17-release-as-fbc/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/fbc_4_17/appstudio.redhat.com/releaseplans/fbc-v4-17-release-as-fbc/releaseplan.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/fbc_4_17/appstudio.redhat.com/releaseplans/fbc-v4-17-release-as-staging-fbc/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/fbc_4_17/appstudio.redhat.com/releaseplans/fbc-v4-17-release-as-staging-fbc/releaseplan.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/fbc_4_17/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/operator/appstudio.redhat.com/releaseplans/cli-manager-operator-release-as-operator/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/operator/appstudio.redhat.com/releaseplans/cli-manager-operator-release-as-operator/releaseplan.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/operator/kustomization.yaml
This PR adds templates and streams for cli manager's file based catalog configurations.
> Add clio file based catalog configurations

- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/projctl.konflux.dev_v1beta1_project_file-based-catalog.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/projctl.konflux.dev_v1beta1_projectdevelopmentstream_cli-manager-operator-fbc-4-17.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/projctl.konflux.dev_v1beta1_projectdevelopmentstreamtemplate_cli-manager-operator-fbc-dst.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/projectl.konflux.dev/projectdevelopmentstreams/file-based-catalog-v4-17/projectdevelopmentstream.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/projectl.konflux.dev/projectdevelopmentstreamtemplates/file-based-catalog/projectdevelopmentstreamtemplate.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/projectl.konflux.dev/projects/file-based-catalog/kustomization.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/projectl.konflux.dev/projects/file-based-catalog/project.yaml
> Add project for pds and pdst

- auto-generated/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/projctl.konflux.dev_v1beta1_projectdevelopmentstreamtemplate_file-based-catalog.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/_base/projectl.konflux.dev/projectdevelopmentstreamtemplates/file-based-catalog/projectdevelopmentstreamtemplate.yaml
> Add resolverref for clio integrationtestscenario

- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/projctl.konflux.dev_v1beta1_projectdevelopmentstreamtemplate_cli-manager-operator-fbc-dst.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/_base/projectl.konflux.dev/projectdevelopmentstreamtemplates/file-based-catalog/projectdevelopmentstreamtemplate.yaml
> Add resolverref in clio PDST

- auto-generated/cluster/stone-prd-rh01/tenants/insights-core-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_insights-yuptoo-tekton-testing.yaml
- cluster/stone-prd-rh01/tenants/insights-core-tenant/insights-yuptoo-app-bonfire-tekton.yaml
- cluster/stone-prd-rh01/tenants/insights-core-tenant/kustomization.yaml
add integration testing for yuptoo
> feat: add integration testing for yuptoo
