redhat-appstudio/tenants-config

- build-manifests.sh
If one of the kustomization directories failed to be build, the script should end with an error.
> Fix build script exit code

- auto-generated/cluster/stone-prd-rh01/gbenhaim-tenant/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/cluster/stone-prd-rh01/gbenhaim-tenant/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/cluster/stone-prd-rh01/gbenhaim-tenant/external-secrets.io_v1beta1_externalsecret_rh-artifacts-bucket-writer.yaml
- auto-generated/lib/app-interface/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/lib/consoledot-ephemeral-env-provider/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/lib/consoledot-test-pipeline/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/lib/consoledot-test-pipeline/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/lib/consoledot-test-pipeline/external-secrets.io_v1beta1_externalsecret_rh-artifacts-bucket-writer.yaml
- auto-generated/lib/rh-artifacts-bucket-writer/external-secrets.io_v1beta1_externalsecret_rh-artifacts-bucket-writer.yaml
- cluster/stone-prd-rh01/gbenhaim-tenant/kustomization.yaml
- lib/app-interface/app-interface.yaml
- lib/app-interface/kustomization.yaml
- lib/consoledot-ephemeral-env-provider/consoledot-ephemeral-env-provider.yaml
- lib/consoledot-ephemeral-env-provider/kustomization.yaml
- lib/consoledot-test-pipeline/kustomization.yaml
- lib/rh-artifacts-bucket-writer/kustomization.yaml
- lib/rh-artifacts-bucket-writer/rh-artifacts-bucket-writer.yaml
The the required external secrets for running the tests of the different consoledot tenants.
depends on https://github.com/redhat-appstudio/infra-deployments/pull/2333
> RHTAP-1201: External secrets for consoledot tests

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/external-secrets.io_v1beta1_externalsecret_rh-fbc-publishing-credentials.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/rh-fbc-publishing-credentials.yaml
> HACBS-2505: add fbc-publishing-credentials for CNV

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/rbac.authorization.k8s.io_v1_rolebinding_cnv-fbc-tenant-release-service-pipeline-rolebinding-dev.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/rbac.authorization.k8s.io_v1_rolebinding_cnv-fbc-tenant-release-service-pipeline-rolebinding-managed.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/v1_serviceaccount_release-service-account.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/rbac.authorization.k8s.io_v1_rolebinding_crt-redhat-acm-tenant-release-service-pipeline-rolebinding-dev.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/rbac.authorization.k8s.io_v1_rolebinding_crt-redhat-acm-tenant-release-service-pipeline-rolebinding-managed.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/v1_serviceaccount_release-service-account.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release-pipeline-sa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release-service-account-build-rb.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/release-pipeline-sa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/release-service-account-build-rb.yaml
- release pipeline service accounts in managed workspaces need access to release type CRs
> Add SAs and Bindings for managed tenants

- build-manifests.sh
Since the -printf argument in find is not compatible with Mac, we get the directories with dirname instead
> Make build-manifests script compatible with Mac

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_releasestrategy_push-to-external-registry-strategy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/release_strategy.yaml
It should use the `pipelineRef` syntax, the previous syntax was deprecated.
> Fix rh release strategy

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy.yaml
This PR includes two commits:
> Use new location for EC data
>
> As part of https://issues.redhat.com/browse/EC-14, the Enterprise
> Contract policy data has a new home. This commit updates the ec-policies
> accordingly.
> Do not pin EC policy data sources
> 
> As learned in https://issues.redhat.com/browse/RHTAPBUGS-856, pinning
> policy data sources can lead to violations due to stale data. This
> commit ensures the lates policy data sources are used.
> 
> It is still recommended to pin the policy rule sources as these refer to
> rego code that needs to be properly gated before deploying. However,
> this process can be cumbersome. https://issues.redhat.com/browse/EC-193
> aims to address this for the EC policies in this repo.
> Update EC policies

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-release-service-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-release-service.yaml
- update of infra-deployments PR should within the development overlay
Depends on https://github.com/redhat-appstudio/infra-deployments/pull/2573
> chore(RHTAPREL-645): use new release overlay

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_terraform-provider-rhcs.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/release-plan-admission/rhtap-migration-rpa.yaml
The Terraform release pipeline needs a GitHub secret to be able to
push the binaries and create a release. In this commit, we are adding
the name of the secret to data to be able to retrieve it from the
release pipeline
> Add GitHub secret to Terraform RPA

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_terraform-provider-rhcs-rhtap.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/release-plan-admission/rhtap-migration-rpa.yaml
Change name of the release pipeline for Terraform from terraform-release to release-to-github-signed to make it more general
> Change name of the release pipeline for Terraform

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1alpha1_releaseplan_internal-services-release-to-quay-rhtap-ser.yaml
- cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/release_plan.yaml
- attempting to see if we can update this label after argo has synced it.
> Remove standing attribution from internal-services

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-build-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-image-controller-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-internal-services-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-release-service-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-remotesecret-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-build.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-image-controller.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-internal-services.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-release-service.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-remotesecret.yaml
- now that https://github.com/redhat-appstudio/release-service-catalog/pull/295 is merged, we can use redhat-appstudio/release-service-catalog
> chore: revert to using main for release pipeline

- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rbac.authorization.k8s.io_v1_rolebinding_tenant-ecp.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rb-ecp.yaml
This will be useful for IntegrationTestScenarios.
> Permit all users to read ECP resources in the central release namespace

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/ec-policy.yaml
See [slack thread here](https://redhat-internal.slack.com/archives/C04RP7SE1ST/p1700663097552329) for details.
There are two changes:
* Waive the requirement for a CycloneDX format SBOM to be created
* Permit the use of `localhost/rhtap-final-image` as a base image
Note that the CVE check, currently failing, is left as-is.
> Modify EC policy config for centos-bootc to get EC checks passing

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/ec-policy.yaml
A followup from #133. The CVEs being detected require upstream fixes and aren't likely to be fixed in the short term.
Rather than skipping the CVE check entirely, we can provide customized rule data so the check will not produce a violation unless critical severity CVEs are found.
This patch can be removed in future when/if the high severity CVEs are fixed.
> Warn only for centos-bootc high severity CVEs

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/ec-policy.yaml
This PR is in favor of https://github.com/redhat-appstudio/tenants-config/pull/135, which should be closed. Merging this will get the ec-policy.yaml files using the OCI bundle and using the latest.
> removing lib directory and replacing with oci bundle

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1alpha1_releaseplan_build-trusted-artifacts-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_build-trusted-artifacts-enterprise-contract.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-build-trusted-artifacts.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/release_plan.yaml
I'm hoping this will allow the image built from the `build-trusted-artifacts` Application from the `rhtap-build-tenant` to be pushed to quay.io/redhat-appstudio repository.
Ref: https://issues.redhat.com/browse/EC-303
> Add release configuration for build-trusted-artacts

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-build-trusted-artifacts-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/kustomization.yaml
This was missing in the initial pull request and results with:
```
no ReleasePlanAdmission found in the target (rh-managed-rhtap-ser-tenant) for application 'build-trusted-artifacts'
```
> Include ReleasePlanAdmission for trusted-artifacts

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-integration-service-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-integration-tenant/appstudio.redhat.com_v1alpha1_releaseplan_integration-service-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-integration-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_integration-service-enterprise-contract.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-integration-service.yaml
- cluster/stone-prd-rh01/tenants/rhtap-integration-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-integration-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtap-integration-tenant/release_plan.yaml
Add integration-service application https://github.com/redhat-appstudio/integration-service
1. add IntegrationTestScneario for integration-service
2. add releasePlan for integration-service for integration-service
3. add releasePlanAdmission for integration-service
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
> feat(STONEINTG-696): add integration-service application

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_o11y-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/integration_test_scenario.yaml
update o11y integartion scenario to grant an
exception until the custom tasks can be run
> chore: update o11y integartion scenario

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_o11y-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/integration_test_scenario.yaml
update o11y integartion scenario to grant an
exception until the custom tasks can be run
> chore: update o11y integration scenario

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_rh-syft-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/integration_test_scenario.yaml
STONEBLD-2004
Use the 'redhat' Enterprise Contract policy (assuming it is the same policy as redhat-no-hermetic but also requires hermetic builds).
Background:
RH-syft is the Syft productization app, lives in the rhtap-build workspace and builds https://github.com/redhat-appstudio/rh-syft.
Its location will likely change when we figure out where Syft really belongs. For now, it will live here so that we can start trying out the productization process.
> Configure EC check for the rh-syft application

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-contract-tenant/appstudio.redhat.com_v1alpha1_releaseplan_ec-v01-alpha-registry-redhat-io.yaml
- cluster/stone-prd-rh01/tenants/rhtap-contract-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtap-contract-tenant/release_plan.yaml
Note that I'm using the rhtas-tenant as an example rather than the example from the documentation. Notably the target is rhtap-releng-tenant and not rh-managed-rhtap-ser-tenant. (Let me know if I'm copying an incorrect example.)
> Add release for EC v0.1 alpha

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-application-service-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-application-service.yaml
This PR adds a ReleasePlanAdmission for HAS, as outlined in the onboarding doc.
The infra-deployments update script I used is the same script that was previously used in HAS:
https://github.com/redhat-appstudio/application-service/blob/948fa4e32d2d2545af439a04750a8a690fe68a19/.tekton/push.yaml#L19-L23
> chore: Add ReleasePlanAdmission for HAS

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1alpha1_releaseplan_rh-syft-registry-redhat-io.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/release_plan.yaml
RH-syft will be released to registry.redhat.io via a ReleasePlanAdmission in the rhtap-releng tenant.
> Add ReleasePlan for the rh-syft application

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/external-secrets.io_v1beta1_externalsecret_registry-redhat-io-pull-secret.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/v1_serviceaccount_appstudio-pipeline.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/external-secrets/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/external-secrets/registry-redhat-io-pull-secret.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/service_account.yaml
The rh-syft build will need to pull base images from
brew.registry.redhat.io. Add an ExternalSecret to make the service
account token available in the rhtap-build-tenant namespace.
Link the resulting Secret to the appstudio-pipeline SA.
> Add registry pull secret for rh-syft builds

- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_quay-token-redhat-acm-remote-secret.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rb-redhat-acm-service-account.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/kustomization.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-quay-token-redhat-acm.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/sa-redhat-acm-service-account.yaml
- To migrate red-hat-acm from tenants to releng, we need SA and Secrets.
> feat(RHTAPREL-722) add red hat acm service aaccount and secret to releng

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_internal-services-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/integration_test_scenario.yaml
IntegrationTestScenario for rhtap-release-2-tenant uses now a policy which exclude hermetic_build_task.
> feat: change policy

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_release-service-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/integration_test_scenario.yaml
IntegrationTestScenario for release-service in rhtap-release-2-tenant uses now a policy which exclude hermetic_build_task.
> feat: update release-service ITS policy

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy-o11y.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy-o11y.yaml
Removed exclusions disallowed_inherited_labels and required_tasks_found since we modified related o11y code.
> chore(RHTAPWATCH-840): Update EC exclusions for o11y

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy-o11y.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy-o11y.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy.yaml
Updates all image references, apart from the ones with the `latest` tag to the currently latest version of EC release policy.
> Update Enterprise Contract release policy

- auto-generated/cluster/stone-prd-rh01/tenants/maestro-rhtap-tenant/appstudio.redhat.com_v1alpha1_releaseplan_maestro-rhtap-releaseplan.yaml
- cluster/stone-prd-rh01/tenants/maestro-rhtap-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/maestro-rhtap-tenant/release-plan.yaml
This PR adds a ReleasePlan for Maestro to reference the newly-created RPA for maestro from https://gitlab.cee.redhat.com/releng/rhtap-release-data/-/merge_requests/179
> Add releaseplan for Maestro

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-tools-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1alpha1_releaseplan_tools-release-to-quay-konflux-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_tools-enterprise-contract.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/kustomization.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-tools.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/release_plan.yaml
Enable tools tenant configs so it can be released
by Konflux.
> chore: enable tools component's tenant configs

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1alpha1_releaseplan_build-service-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1alpha1_releaseplan_build-trusted-artifacts-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1alpha1_releaseplan_image-controller-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-gitops-tenant/appstudio.redhat.com_v1alpha1_releaseplan_release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-has-tenant/appstudio.redhat.com_v1alpha1_releaseplan_application-service-release-to-quay-konflux-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-integration-tenant/appstudio.redhat.com_v1alpha1_releaseplan_integration-service-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1alpha1_releaseplan_o11y-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1alpha1_releaseplan_release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/appstudio.redhat.com_v1alpha1_releaseplan_tools-release-to-quay-konflux-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1alpha1_releaseplan_internal-services-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1alpha1_releaseplan_release-service-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-spi-tenant/appstudio.redhat.com_v1alpha1_releaseplan_remotesecret-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-spi-tenant/appstudio.redhat.com_v1alpha1_releaseplan_spi-release-to-quay-rhtap-ser.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/release_plan.yaml
- cluster/stone-prd-rh01/tenants/rhtap-gitops-tenant/release_plan.yaml
- cluster/stone-prd-rh01/tenants/rhtap-has-tenant/release_plan.yaml
- cluster/stone-prd-rh01/tenants/rhtap-integration-tenant/release_plan.yaml
- cluster/stone-prd-rh01/tenants/rhtap-o11y-tenant/release_plan.yaml
- cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/release_plan.yaml
- cluster/stone-prd-rh01/tenants/rhtap-spi-tenant/release_plan.yaml
- As part of this commit targets for RPA are updated
to point to the new location, `rhtap-releng-tenant.`
- At this point, all the RPA has already migrated to
a new location.
- Ref: Migration [MR](https://gitlab.cee.redhat.com/releng/rhtap-release-data/-/merge_requests/145)
- Jira: [RHTAPREL-723](https://issues.redhat.com/browse/RHTAPREL-723)
> feat(RHTAPREL-723): update releaseplan target to releng tenant

- auto-generated/cluster/stone-prd-rh01/tenants/rh-acs-tenant/appstudio.redhat.com_v1alpha1_releaseplan_rh-acs-fast-stream.yaml
- cluster/stone-prd-rh01/tenants/rh-acs-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rh-acs-tenant/release_plan.yaml
Following the creation of the ReleasePlanAdmission and constraints configuration in https://gitlab.cee.redhat.com/releng/rhtap-release-data/-/merge_requests/195, this shall create the ReleasePlan for ACS.
> ROX-22546: create ReleasePlan for RHACS

- auto-generated/cluster/stone-prd-rh01/tenants/konflux-infra-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/konflux-infra-tenant/integration_test_scenario.yaml
It currently using a policy that differs from te policy we use for the release (which is more permissive).
Make it optional so we can improve as build as we go without blocking the release.
> konflux-infra: make integ ec test optional

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_bootc-image-builder.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_centos-bootc.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fedora-bootc.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-staged-index-release-v4-15-plus.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_fbc-staged-index-release.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_hypershift-operator-rpa.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_releaseplanadmission_rhtap-build-trusted-artifacts-rpa.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/release-plan-admission/bootc-image-builder.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/release-plan-admission/centos-bootc.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/release-plan-admission/fedora-bootc.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release_plan_admission_stage_index.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/release_plan_admission_stage_index_v4_15_plus.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/release_plan_admission.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/release_plan_admission-build-trusted-artifacts.yaml
This commit updates the `release-service catalog` reference
as result of migration to `konflux-ci` from `redhat-appstudio`
more details parent EPIC:
https://issues.redhat.com/browse/RHTAPREL-800
> feat(RELEASE-500): update release service catalog reference to konflux-ci

- auto-generated/cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/appstudio.redhat.com_v1alpha1_application_maestro-main.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/appstudio.redhat.com_v1alpha1_component_maestro-addon-main.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/appstudio.redhat.com_v1alpha1_component_maestro-main.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/README.md
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/base/component.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/base/kustomization.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/overlay/maestro/base/application.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/overlay/maestro/base/kustomization.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/overlay/maestro/base/maestro-addon/kustomization.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/overlay/maestro/base/maestro-addon/maestro-addon.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/overlay/maestro/base/maestro/kustomization.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/overlay/maestro/base/maestro/maestro.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/overlay/maestro/main/application-patch.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/overlay/maestro/main/component-patch.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro/overlay/maestro/main/kustomization.yaml
Maestro is being used standalone as a service out of the openshift-online organization.  ACM is maintaining a product fork of this project in stolostron/maestro and maestro-addon (for ACM).  This PR uses the [casc model](https://github.com/konflux-ci/casc-gpt/tree/main) to onboard this application and components.
> Onboard the Maestro Project as part of ACM via Configuration-as-Code

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-migration-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_ingress-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/rhtap-migration-tenant/insights-ingress-go-clowder-test.yaml
- cluster/stone-prd-rh01/tenants/rhtap-migration-tenant/kustomization.yaml
I'm testing a new model for the Clowder integration for teams to add the parameters in the pipeline in their own repos instead of here
> feat(RHTAPWATCH-869): test new clowder model

- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_infra-deployments-pr-creator-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_quay-token-konflux-ci-secret-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/appstudio.redhat.com_v1beta1_remotesecret_send-slack-notification-secret-remote-secret.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rbac.authorization.k8s.io_v1_rolebinding_konflux-servicerelease-rb.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rhtap-releng-tenant/v1_serviceaccount_konflux-ci-servicerelease-sa.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/rb-konflux-service-release.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-infra-deployments-pr-creator.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-quay-token-konflux-ci.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/remote-secrets/remote_secret-send-slack-notification.yaml
- cluster/stone-prd-rh01/managed/rhtap-releng-tenant/sa-konflux-service-release.yaml
There is some bug in `cosign` such that if two secrets are both linked
to push to quay, cosign doesn't know how to sort things out and use the
right one.
To workaround, we need two different serviceaccounts here: one for
pushing to quay.io/redhat-appstudio and one for pushing to
quay.io/konflux-ci.
> Create a second SA for konflux-ci releases

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1alpha1_releaseplan_build-service-release-to-quay-rhtap-ser.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_build-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/release_plan.yaml
STONEBLD-1987
Long ago, someone tried to onboard build-service to Konflux under the
'build' application. Now, we are finally re-onboarding for real.
Rename the application to 'build-service' to match the naming scheme
used for all the other Build team components.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>
> rhtap-build: update build-service app name

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/external-secrets.io_v1beta1_externalsecret_quay-push-secret.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/external-secrets/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/external-secrets/quay-push-secret.yaml
STONEBLD-1937
We're onboarding build-service to Konflux, but build-service already has Tekton pipelines running in the tekton-ci namespace. Because of that, build-service cannot be onboarded to the rhtap-build-tenant namespace (see https://pipelinesascode.com/docs/guide/repositorycrd/ ):
* the Repository is already present in the tekton-ci namespace
* the Repository must only exist in one namespace
* the pipelines must run in the same namespace
To avoid losing CI completely for an extended period of time, we want to keep the old pipelines working while we slowly onboard to Konflux. That means we need to move the old pipelines from the tekton-ci namespace to the rhtap-build-tenant namespace.
To do that, we need to:
* delete Repo from tekton-ci (in redhat-appstudio/infra-deployments)
* add …
> Run build-service pipelines in rhtap-build-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/appstudio.redhat.com_v1alpha1_releaseplan_maestro.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/release-plan.yaml
This PR adds a ReleasePlan for the Maestro application in the crt-redhat-acm workspace to reference the RPA created [here](https://gitlab.cee.redhat.com/releng/konflux-release-data/-/commit/088c4fb26e17597c25e498dff1481340150f2e4a).
> Add ReleasePlan for the maestro application in crt-redhat-acm

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_build-task-dockerfile-e2e-test.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/integration_test_scenario.yaml
This PR adds the integration test for running the e2e-tests in the rhtap-build-tenant ns.
Part of the story: https://issues.redhat.com/browse/STONEBLD-2353
> feat: Add the integration test for running e2e-test

- auto-generated/cluster/stone-prd-rh01/tenants/sfo-security-tenant/appstudio.redhat.com_v1alpha1_releaseplan_sfo-release-as-service.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/sfo-security-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_sfo-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/sfo-security-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/sfo-security-tenant/release_plan.yaml
Fixing the naming of application field to reflect proper name of application splunk-forwarder-operator
> Modified sfo-security to reflect the correct application naming

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_platform-feedback-bonfire-tekton.yaml
- cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/integration_test_tekton.yaml
- cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/kustomization.yaml
Adding bonfire-tekton integration test to hcc-accessmanagement-tenant for application and component: platform-feedback.
> Adding bonfire-tekton integration test to hcc-accessmanagement-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/appstudio.redhat.com_v1alpha1_releaseplan_notifications-release-as-ms.yaml
- cluster/stone-prd-rh01/tenants/hcc-notifications-tenant/notifications_release_plan.yaml
HCC Notifications is creating lots of releases (sometimes more than 100 a day) so we need the release CR garbage collector to delete release snapshots more aggressively so that we don't hit the snapshots quota in Konflux.
> Add releaseGracePeriodDays to HCC Notifications release plan

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_cloud-connector-tekton-insights.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/cloud_connector_tekton_test.yaml
I want to configure cloud-connector to use a custom set of cicd scripts which are located here:  https://github.com/dehort/cicd-tools 
on branch: change_component_name_to_clowd_app_name_for_deploy_iqe_cji
Will this do that?
> Modify cloud-connector to use a custom version of the bonfire cicd scripts

- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy-cnv.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-fbc-stage-index-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_app-interface-standard.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy-o11y.yaml
- auto-generated/cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_rh-policy.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-migration-tenant/appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_consoledot-frontend-standard.yaml
- cluster/stone-prd-rh01/managed/rh-managed-bifrost-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-cnv-fbc-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-mng-s-2-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-red-hat-acm-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy-o11y.yaml
- cluster/stone-prd-rh01/managed/rh-managed-rhtap-ser-tenant/ec-policy.yaml
- cluster/stone-prd-rh01/tenants/rhtap-migration-tenant/consoledot-frontend-standard-policy.yaml
STONEBLD-2339
All the images built in build-definitions CI now get released to the
quay.io/konflux-ci organization.
Replace the relevant redhat-appstudio[-tekton-catalog] references in
this repo with konflux-ci[/tekton-catalog] references.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>
> Migrate build-definitions redhat-appstudio images

- auto-generated/cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_maestro-main-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/maestro.enterprise-contract.integrationtestscenario.yaml
This PR adds an IntegrationTestScenario for the Maestro on-prem deliverable.  We haven't determined which on-prem gate to use yet, so we'll use this services-standard policy to match the current gate in the RPA.
> Add EnterpriseContract ITS for Maestro

- auto-generated/cluster/stone-prd-rh01/tenants/rh-hms-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_provisioning-frontend-bonfire-tekton.yaml
- cluster/stone-prd-rh01/tenants/rh-hms-tenant/provisioning-frontend-integration.yaml
Adding the fix: https://github.com/RedHatInsights/bonfire-tekton/commit/c30f877c2492568fc95d4d43e5c6d5bf2fabf65f
> Correct Insights spelling. 

- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1alpha1_releaseplan_helm-operator.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_helm-operator-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/operator/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/operator/release-plan.yaml
Remove prefix `orchestrator` from `ReleasePlan` and `IntegrationTestScenario` manifests to align with renamed component.
@ralphbean @rgolangh PTAL.
> [orchestrator-releng] Update component name references to helm-operator

- auto-generated/cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_hypershift-operator-main-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rh-acs-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_acs-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/hypershift-operator-main/enterprise-contract.integrationtestscenario.yaml
- cluster/stone-prd-rh01/tenants/rh-acs-tenant/integration_test_scenario.yaml
Here from this comment - https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/521#note_11100967 
Out of all the policy name changes in https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/521
```
registry-rhacs -> registry-rh-acs  # Updated in this MR
app-interface-hypershift -> app-interface-crt-redhat-acm  # Updated in this MR
registry-rhtpa -> registry-trusted-content  # Not found in the repo
app-interface-clio-wrklds -> app-interface-clio-wrklds-pipeline  # Not found in the repo
```
This MR reflects changes to the names that I found in this repo. 
cc - @ralphbean
> Update policy names as per CLOUDDST-22158

- auto-generated/cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_acrobot-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/kustomization.yaml
Hi! I'm doing my best to follow the Red Hat [guide](https://docs.google.com/document/d/1bKE4pmrufEb1QROo7XhMVEmUClc--WtAmX1__rxNscc/edit) for adding a new application in order to host the Slack version of Acrobot.
I apologize if I'm doing this wrong or if this is in the wrong place.
> Add acrobot-slack-tenant

- auto-generated/cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_osde2e-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/kustomization.yaml
add back the EC with POLICY_CONFIGURATION set to tmp-onboard-policy
> osde2e-cicada: add tmp EC

- auto-generated/cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/appstudio.redhat.com_v1alpha1_releaseplan_siteconfig.yaml
- cluster/stone-prd-rh01/tenants/crt-redhat-acm-tenant/release-plan.yaml
This PR adds a ReleasePlan for SiteConfig now that https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/671 is merged to add it to our RPA
> Add siteconfig ReleasePlan

- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1alpha1_releaseplan_fbc-v4-14-release-as-production-fbc.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1alpha1_releaseplan_fbc-v4-14-release-as-staging-fbc.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_fbc-v4-14-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/fbc-v4-14/integrationtestscenarios/enterprise-contract/integrationtestscenario.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/fbc-v4-14/integrationtestscenarios/enterprise-contract/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/fbc-v4-14/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/fbc-v4-14/releaseplans/production/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/fbc-v4-14/releaseplans/production/releaseplan.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/fbc-v4-14/releaseplans/staging/kustomization.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/fbc-v4-14/releaseplans/staging/releaseplan.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/kustomization.yaml
Adds the ReleasePlans manifests for the Orchestrator Operator
> [orchestrator-releng] Add FBC ReleasePlan manifests for OCP 4.14

- auto-generated/cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_cli-manager-operator.yaml
- cluster/stone-prd-rh01/tenants/clio-wrklds-pipeline-tenant/release-plan.yaml
This PR renames the application name in cli manager release plan to `cli-manager-operator`.
> Rename clio application name to cli-manager-operator

- auto-generated/cluster/stone-prd-rh01/tenants/pulp-services-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_pulp-bonfire-tekton.yaml
- cluster/stone-prd-rh01/tenants/pulp-services-tenant/pulp-bonfire-tekton.yaml
Otherwise I get:
```
[User error] PipelineRun pulp-services-tenant parameters is missing some parameters required by Pipeline pulp-c8v4d-22nnb's parameters: pipelineRun missing parameters: [IQE_PLUGINS]
```
We're using this PR, and I got the go ahead to use it: https://github.com/RedHatInsights/bonfire-tekton/pull/35
PULP-110
> Fix Pulp not running with the PR for basic_no_iqe.yaml

- auto-generated/cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_acrobot-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/dvo-obsint-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_deployment-validation-operator-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_platform-feedback-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_osde2e-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_api-frontend-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/acrobot-slack-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/dvo-obsint-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/hcc-accessmanagement-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/rh-platform-experien-tenant/integration_test_scenario.yaml
The build-definitions repo was moved, so let's update these references.
Ref: https://issues.redhat.com/browse/EC-683
> Update ITS pipeline resolvers to new location

- auto-generated/cluster/stone-prd-rh01/tenants/oeo-cicada-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_oeo-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/oeo-cicada-tenant/integration_test_scenario.yaml
bundle images are not passing preflight checks, this is causing the ECP
to fail and block development. This should be added back once the issue
with the preflight check is resolved
https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1719559548542999?thread_ts=1719475396.888239&cid=C04PZ7H0VA8
> SDCICD-1329: temporarly drop POLICY_CONFIGURATION

- auto-generated/cluster/stone-prd-rh01/tenants/centos-bootc-tenant/appstudio.redhat.com_v1alpha1_application_bootc-c9s.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/centos-bootc-tenant/appstudio.redhat.com_v1alpha1_component_bootc-image-builder-c9s.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/centos-bootc-tenant/appstudio.redhat.com_v1alpha1_component_centos-bootc-c9s.yaml
- cluster/stone-prd-rh01/tenants/centos-bootc-tenant/bootc-c9s.yaml
- cluster/stone-prd-rh01/tenants/centos-bootc-tenant/kustomization.yaml
centos-c9s application with two components:
- centos-bootc-c9s
- bootc-image-builder-c9s
This application will replace two applications:
- centos-bootc-c9s
- bootc-image-builder (which disappeared recently from the cluster)
> bootc-c9s application

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-build-tenant/external-secrets.io_v1beta1_externalsecret_snyk-secret.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/external-secrets/kustomization.yaml
- cluster/stone-prd-rh01/tenants/rhtap-build-tenant/external-secrets/snyk-secret.yaml
Currently, the rhtap-build workspace uses a personal Snyk API token. Switch to the same token used in the tekton-ci namespace - a service account token for the developer-red-hat-trusted-application-pipeline organization.
This is to:
* avoid the warning about approaching the monthly limit of 100 tests
* allow rhtap-build pipelines to upload results to the organization
> rhtap-build: use shared Snyk token

- auto-generated/cluster/stone-prd-rh01/tenants/insights-runtimes-tenant/appstudio.redhat.com_v1alpha1_releaseplan_runtimes-inventory-operator-release-as-product.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/insights-runtimes-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_runtimes-inventory-operator-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/insights-runtimes-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/insights-runtimes-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/insights-runtimes-tenant/release_plan.yaml
This PR adds a ReleasePlan for runtimes-inventory-operator, and changes the policy in our IntegrationTestScenario.
> Add ReleasePlan for runtimes-inventory-operator

- auto-generated/cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/appstudio.redhat.com_v1alpha1_application_osde2e.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/appstudio.redhat.com_v1alpha1_component_osde2e-main.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/appstudio.redhat.com_v1alpha1_imagerepository_imagerepository-for-osde2e-osde2e-main.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/application.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/component.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/image_repository.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/integration_test_scenario.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/osde2e-cicada-tenant/release_plan.yaml
add the application and component for osde2e to be fully onboarded onto
the casc model. These resources exist already, so hopefully argocd
adopts them properly
> SDCICD-1306: onboard entire configuration

- auto-generated/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/projctl.konflux.dev_v1beta1_project_file-based-catalog.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/projctl.konflux.dev_v1beta1_projectdevelopmentstream_file-based-catalog-v4-16.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/projctl.konflux.dev_v1beta1_projectdevelopmentstreamtemplate_file-based-catalog.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/_base/kustomization.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/_base/projectl.konflux.dev/projectdevelopmentstreams/file-based-catalog-v4-16/kustomization.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/_base/projectl.konflux.dev/projectdevelopmentstreams/file-based-catalog-v4-16/projectdevelopmentstream.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/_base/projectl.konflux.dev/projectdevelopmentstreamtemplates/file-based-catalog/kustomization.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/_base/projectl.konflux.dev/projectdevelopmentstreamtemplates/file-based-catalog/projectdevelopmentstreamtemplate.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/_base/projectl.konflux.dev/projects/file-based-catalog/kustomization.yaml
- cluster/stone-prd-rh01/tenants/multiarch-tuning-ope-tenant/_base/projectl.konflux.dev/projects/file-based-catalog/project.yaml
This PR configure a multi-version project for the FBC of the multiarch-tuning-operator, starting from 4.17 and leaving 4.16 to the UI/manual creation
> MULTIARCH-4784: Multi-version configuration for the multiarch-tuning-operator FBC

- auto-generated/cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_helm-operator-enterprise-contract.yaml
- cluster/stone-prd-rh01/tenants/orchestrator-releng-tenant/operator/integration_test_scenario.yaml
Use dedicated policy for building the orchestrator's operator container images
> [orchestrator-releng] Use dedicated policy for IntegrationTestScenarios

- auto-generated/cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/appstudio.redhat.com_v1alpha1_releaseplan_payload-tracker-frontend-release-as-ms.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/hcc-pipeline-tenant/payload-tracker-frontend_release_plan.yaml
Part of [RHCLOUD-32758](https://issues.redhat.com/browse/RHCLOUD-32758)
Added release plan for payload-tracker-frontend
cc @scoheb @gbenhaim
> Create payload-tracker-frontend release plan

- auto-generated/cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/appstudio.redhat.com_v1alpha1_releaseplan_release-service-monitor-release-to-quay-rhtap-ser.yaml
- cluster/stone-prd-rh01/tenants/rhtap-release-2-tenant/release_plan.yaml
This commit adds the RP for release-service-monitor to Konflux to release the application.
> chore: onboard release-service-monitor to Konflux

- auto-generated/cluster/stone-prd-rh01/tenants/console-platex-services-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_quickstarts-bonfire-tekton.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/console-platex-services-tenant/appstudio.redhat.com_v1beta2_integrationtestscenario_quickstarts-enterprise-contract.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/console-platex-services-tenant/external-secrets.io_v1beta1_externalsecret_app-interface.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/console-platex-services-tenant/external-secrets.io_v1beta1_externalsecret_consoledot-ephemeral-env-provider.yaml
- auto-generated/cluster/stone-prd-rh01/tenants/console-platex-services-tenant/external-secrets.io_v1beta1_externalsecret_rh-artifacts-bucket-writer.yaml
- cluster/stone-prd-rh01/tenants/console-platex-services-tenant/kustomization.yaml
- cluster/stone-prd-rh01/tenants/console-platex-services-tenant/quickstarts-bonfire-tekton.yaml
- cluster/stone-prd-rh01/tenants/console-platex-services-tenant/quickstarts-integration.yaml
Enable enterprise contract for [quickstarts api](https://github.com/RedHatInsights/quickstarts)
> [RHCLOUD-30197] Add quickstarts-enterprise-contract and bonfire integration

- cluster/stone-prd-rh01/tenants/ose-osc-tenant/openshift-sandboxed-containers-openshift-tests-private.yaml
it runs existing integration tests from openshift-tests-private and includes token for the secret to authenticate for the private repo
> create new integration test scenario for openshift sandboxed containers
